sonar.organization=yahyaouiichrak
sonar.projectKey=s-p-auth-service
sonar.projectName=SamraPerfumes Auth-Service

# Paths relatifs à la racine du repo
sonar.sources=apps/auth-service/src
sonar.tests=apps/auth-service/tests

# Coverage path
sonar.javascript.lcov.reportPaths=apps/auth-service/coverage/lcov.info

# Exclusions
sonar.coverage.exclusions=**/*.test.js,**/tests/**,**/node_modules/**
sonar.test.inclusions=**/*.test.js

# Language
sonar.language=js

# Encoding
sonar.sourceEncoding=UTF-8

# Scan only auth-service folder
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,apps/product-service/**,apps/order-service/**,apps/payment-service/**,apps/ai-service/**,apps/notification-service/**